Update detect

diff --git a/buildpack/bin/detect b/buildpack/bin/detect
--- a/buildpack/bin/detect
+++ b/buildpack/bin/detect
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
-for f in jreleaser.*; do
-  if [ -e "$f" ]; then
-    exit 0
-  else
-    exit 100
-  fi
-done
+# Check for the presence of JReleaser configuration files
+if [ -f "${1}/jreleaser.yaml" ] || [ -f "${1}/jreleaser.toml" ] || [ -f "${1}/jreleaser.json" ]; then
+  # JReleaser configuration file found, return success
+  echo "JReleaser config file detected"
+  exit 0
+else
+  # No JReleaser configuration file found, return failure
+  echo "No JReleaser config file detected"
+  exit 1
+fi
